services:
  application:
    container_name: "laravel-duckpay"
    build:
      context: ./docker/
      dockerfile: php.Dockerfile
    working_dir: /var/duckpay
    command: "php artisan serve --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/var
    networks:
      - networks-laravel-duckpay
    ports:
      - 80:8000

  node:
    container_name: "node-duckpay"
    build:
      context: ./docker/
      dockerfile: node.Dockerfile
    working_dir: /var/duckpay/duckpay
    command: "npm run dev"
    volumes:
      - ./:/var
    networks:
      - networks-laravel-duckpay
    ports:
      - 5173:5173
      - 9000:9000

networks:
  networks-laravel-duckpay:
    driver: bridge
